### ISSUE TITLE
Mistake in Pedigree.py Line 165

### ISSUE THREAD

**Issue by augustusgrant** [AlphaGenes/tinyhouse#12]
https://github.com/AlphaGenes/tinyhouse/blob/65456ea92e58fc40886fa1d1654b3a66443f28b4/Pedigree.py#L165
"sire" is referenced twice, I believe one should be "dam".

This is within the `getGenotypedFounderStatus()` function, and causes some individuals to be incorrectly identified as the first to be genotyped, e.g. if their mother is genotyped and their father is not.

https://github.com/AlphaGenes/tinyhouse/blob/65456ea92e58fc40886fa1d1654b3a66443f28b4/Pedigree.py#L156-L176

I noticed this because it is giving me incorrect results in AlphaPeel.  Genotyped founder status is used in the arbitrary phasing of heterozygotes in founders, which are all assigned as genotype=10 (minor allele inherited from father).  
https://github.com/AlphaGenes/AlphaPeel/blob/1c56d89e49b78b23c6ef6b3651164448697097f7/src/tinypeel/Peeling/PeelingInfo.py#L57-L61

For example, when run on the following very simple single locus data,
`ped.txt =`
```
A 0 0
B 0 0
C A B
```
`gen.txt =`
```
A 9
B 2
C 1
```
AlphaPeel will output the following dosages (using all other default parameters):
`out.dosages =`
```
A 1.2978
B 1.0987
C 1.1982
```

Despite specifying the genotype of B as 2, the AlphaPeel estimate is around 1.  This is because C is incorrectly set as a founder and has its phasing assigned to inherit the minor allele from the father (A).

Modifying Pedigree.py fixed this error for me. 

Thanks.

**Comment by gregorgorjanc** [comment]
@augustusgrant thanks for hunting down this bug and reporting it! I have applied the fix;)

**Comment by augustusgrant** [comment]
Thank you very much for the quick fix!  Took me a while to find the exact cause, but I knew something wasn't quite right.
